spring.application.name=AgropapinAPI

# Spring DataSource Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# InfluxDB Configuration
influxdb.url=${INFLUX_URL}
influxdb.token=${INFLUX_TOKEN}
influxdb.org=AgroPapinOrg
influxdb.bucket=PapinSensorData


#  Configuración de Spring AI
spring.ai.openai.api-key=${OPENAI_TOKEN}
spring.ai.openai.chat.options.model=gpt-4o-mini

# MQTT Broker Configuration
mqtt.broker.url=${MQTT_URL}
mqtt.client.id=${MQTT_USERNAME}
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}

# Spring Data JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.agropapin.backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7

# Spring Oauth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-1v0pinwnl2kuwsf1.us.auth0.com/

logging.level.com.agropapin.backend=DEBUG
logging.level.com.agropapin.backend.telemetryingestion=DEBUG